[book]
title = "HEC-DSS Rust Library"
authors = ["hatch-tyler"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/hatch-tyler/hec-dss-rs"
